version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
    - env:
      - CGO_ENABLED=0
      goos:
        - darwin
        - linux
        - windows
      goarch:
        - amd64
        - arm64
      ignore:
        - goarch: arm64
          goos: windows
archives:
  - formats: ['tar.gz']
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}{{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ['zip']
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
release:
  github:
    owner: sivaprasadreddy
    name: progen
  name_template: "{{.Tag}}"

brews:
  - name: "progen"
    homepage: "https://github.com/sivaprasadreddy/progen"
    description: "Project Generator CLI"
    repository:
      owner: sivaprasadreddy
      name: homebrew-progen
    commit_author:
      name: K Siva Prasad Reddy
      email: sivaprasadreddy.k@gmail.com
    directory: Formula
    test: |
      system "#{bin}/progen --version"
    install: |
      bin.install "progen"
